### PR TITLE
pe fix

### LINKED ISSUE #247: [PE-D][Tester A] Bug: Information truncated in user interface
When I try to add a user with long name, email, and address, information is truncated in the GUI

Steps to reproduce (Run the following in sequence):
1. add --name=Jose Maria Alejandro Maximiliano Sebastian Fernando --phone=87654321 --email=blahblahlittlesheeplittlestar@example.com --address=10 Anson Road, #27-15, International Plaza, Singapore 079903add --name=Jose Maria Alejandro Maximiliano Sebastian Fernando --phone=87654321 --email=blahblahlittlesheeplittlestar@example.com --address=10 Anson Road, #27-15, International Plaza, Singapore 079903
2. view {index of the record that is added from above}

Expected:
Information such as address which are important should not be truncated but instead, should be wrapped like the name 

Actual:
Image

Alternative example from the starter data provided
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #271: [PE-D][Tester E] Email and address become unreadable at the minimum window width
Relevant spec: UG PDF p.2 states that the right panel shows the selected client’s full details.

Steps to reproduce:
1. Start Linkline with fresh sample data.
2. Resize the main window to the smallest width the app allows.
3. Run view 1.
4. Look at the email address and address shown in the right-hand details panel.

Expected: The selected client’s full email address and address should still be readable, or the UI should provide a way to access the hidden text such as wrapping or horizontal scrolling.

Actual: The email address and address are truncated, for example alexyeoh@exa..., and there is no way to scroll horizontally in the right panel to read the hidden text.

Notes: The app allows the user to resize the window to this width, but at that size the details pane no longer shows the client’s full contact details. This makes some important information inaccessible during normal use, especially for users working in a narrow or split-screen layout. Possibly users who are using old computers with lower resolution monitors may face issues with long email addresses / addresses cutting off. 

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by huiyi-Al**

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ public void deletePerson(Person target) {
     @Override
     public void addPerson(Person person) {
         addressBook.addPerson(person);
-        resetPredicatesFilteredPersonList();
+
```
Comment (kihoo56tkr) [inline src/main/java/seedu/address/model/ModelManager.java]: I think we want the filtered list to be reset if a user adds a new client (similar to what happens in `deletetag` and `renametag`)

**Review by kihoo56tkr — CHANGES_REQUESTED** [review]
Changes:
1. Please change back the addPerson line that you have removed.
2. You did not solve the issue (see #243) of the ambigious instruction in the details panel during startup. You can change it to something like 'Use view command to view client's details' or 'Type "view INDEX" (e.g., "view 1") to view their details'
Other than these, the rest are fine. Thanks.

**Review by kihoo56tkr — APPROVED** [review]
LGTM
